export const NAVIGATE_LOGIN_PAGE = 'NAVIGATE_LOGIN_PAGE';
export const NAVIGATE_HOME_PAGE = 'NAVIGATE_HOME_PAGE';

// STAFF
export const STAFF_UPDATE_ONLINE_LIST = 'STAFF_UPDATE_ONLINE_LIST';

//CALL
export const CALL_EVENT_UPDATE_DURATION = 'CALL_EVENT_UPDATE_DURATION';
export const CALL_EVENT_UPDATE = 'CALL_EVENT_UPDATE';
export const CALL_EVENT_PHONE_UPDATE = 'CALL_EVENT_PHONE_UPDATE';
export const CALL_EVENT_USER_INFO_UPDATE = 'CALL_EVENT_USER_INFO_UPDATE';
export const GLOBAL_CALL_DATA_UPDATE = 'GLOBAL_CALL_DATA_UPDATE';

//COMMON
export const SHOW_DISCONNECT = 'SHOW_DISCONNECT';
export const UPDATE_UNREAD_COUNT = 'UPDATE_UNREAD_COUNT';

// SETTING
export const CHANGE_FONT_STYLE = 'CHANGE_FONT_STYLE';
export const CHANGE_FONT_SIZE = 'CHANGE_FONT_SIZE';
export const CHANGE_PRIMARY_THEME = 'CHANGE_PRIMARY_THEME';
export const CHANGE_SECONDARY_THEME = 'CHANGE_SECONDARY_THEME';
export const CHANGE_DARK_THEME = 'CHANGE_DARK_THEME';
export const CHANGE_COMMON_SETTING = 'CHANGE_COMMON_SETTING';

// CALL LOG LIST
export const OPEN_CALL_LOG_BY_NAME = 'OPEN_CALL_LOG_BY_NAME';

// CALL LOG LIST
export const REQUIRED_RELOAD = 'REQUIRED_RELOAD';

// EXPAND HISTORY
export const EXPANDED_HISTORY = 'EXPANDED_HISTORY';
